#!/usr/bin/env python3
"""Writes symbols.zon: xschem's device symbols as NetlistParser classes.

    python3 gen_symbols.py <xschem_library/devices> > symbols.zon

Each class's terminals sit where the xschem symbol's pins are, turned into
NetlistParser's canonical frame: xschem draws devices upright, the canonical
frame is horizontal, and the layout's upright form is the canonical frame
turned a quarter left (Orient.left). So a canonical anchor is the xschem pin
turned a quarter right, (x, y) -> (-y, x), and a device the layout stands
upright lands every pin on xschem's own coordinates. Terminals are listed in
SPICE node order. Strokes (lines, polygons, arcs) come along so the SVG and
TikZ renderers draw what xschem draws.
"""
import math
import re
import sys

# class, symbol, pins in SPICE node order, pins the layout leaves unwired, role
TABLE = [
    ("res", "res", ["P", "M"], [], None),
    ("cap", "capa", ["p", "m"], [], None),
    ("ind", "ind", ["p", "m"], [], None),
    ("vsource", "vsource", ["p", "m"], [], None),
    ("isource", "isource", ["p", "m"], [], None),
    ("diode", "diode", ["p", "m"], [], None),
    ("bsource", "bsource", ["p", "m"], [], None),
    ("cvsource", "vcvs", ["p", "m", "cp", "cm"], [], None),
    ("cisource", "vccs", ["p", "m", "cp", "cm"], [], None),
    ("ccvs", "ccvs", ["p", "m"], [], None),
    ("cccs", "cccs", ["p", "m"], [], None),
    ("nmos", "nmos4", ["d", "g", "s", "b"], ["b"], None),
    ("pmos", "pmos4", ["d", "g", "s", "b"], ["b"], None),
    ("npn", "npn", ["C", "B", "E"], [], None),
    ("pnp", "pnp", ["C", "B", "E"], [], None),
    ("njfet", "njfet", ["d", "g", "s"], [], None),
    ("pjfet", "pjfet", ["d", "g", "s"], [], None),
    ("switch", "switch", ["P", "M", "CP", "CM"], [], None),
    ("vdd", "vdd", ["p"], [], "power_rail"),
    ("gnd", "gnd", ["p"], [], "ground_rail"),
    ("ipin", "ipin", ["p"], [], "input_port"),
    ("opin", "opin", ["p"], [], "output_port"),
]


def turn(x, y):
    """xschem (upright) -> canonical: a quarter turn right, rounded."""
    return (round(-y), round(x))


def parse(path):
    pins, ops = {}, []
    for line in open(path):
        f = line.split()
        if not f:
            continue
        if f[0] == "B" and f[1] == "5":
            x1, y1, x2, y2 = map(float, f[2:6])
            name = re.search(r"name=([^\s}]+)", line).group(1)
            pins[name] = ((x1 + x2) / 2, (y1 + y2) / 2)
        elif f[0] == "L":
            x1, y1, x2, y2 = map(float, f[2:6])
            ops.append(("line", [turn(x1, y1), turn(x2, y2)]))
        elif f[0] == "B":
            x1, y1, x2, y2 = map(float, f[2:6])
            ops.append(("poly", [turn(x1, y1), turn(x2, y1), turn(x2, y2), turn(x1, y2), turn(x1, y1)]))
        elif f[0] == "P":
            n = int(f[2])
            v = list(map(float, f[3 : 3 + 2 * n]))
            ops.append(("poly", [turn(v[2 * i], v[2 * i + 1]) for i in range(n)]))
        elif f[0] == "A":
            x, y, r, a, b = map(float, f[2:7])
            if b >= 360:
                cx, cy = turn(x, y)
                ops.append(("circle", (cx, cy, round(r))))
            else:
                # xschem arcs run counter-clockwise from `a`, y down.
                steps = max(4, int(abs(b) / 15))
                pts = [turn(x + r * math.cos(math.radians(a + b * i / steps)), y - r * math.sin(math.radians(a + b * i / steps))) for i in range(steps + 1)]
                ops.append(("poly", pts))
    return pins, ops


def pt(p):
    return f".{{ .x = {p[0]}, .y = {p[1]} }}"


def main(devices):
    out = [
        "// xschem's device symbols as NetlistParser classes, generated by",
        "// gen_symbols.py from the xschem 3.4.7 devices library. Pins sit where",
        "// xschem's are (turned into the canonical frame: see the script), so",
        "// the layout's wires end on them exactly. One unit is 60, xschem's pin",
        "// to pin length for a two-pin symbol.",
        ".{",
        "    .unit = 60,",
        "    .classes = .{",
    ]
    for cls, sym, order, hidden, role in TABLE:
        pins, ops = parse(f"{devices}/{sym}.sym")
        terms = []
        for name in order:
            x, y = pins[name]
            extra = ", .hidden = true" if name in hidden else ""
            terms.append(f'.{{ .name = "{name}", .at = {pt(turn(x, y))}{extra} }}')
        draw = []
        for kind, data in ops:
            if kind == "line":
                if data[0] != data[1]:
                    draw.append(f".{{ .line = .{{ .a = {pt(data[0])}, .b = {pt(data[1])} }} }}")
            elif kind == "poly":
                draw.append(".{ .polyline = .{ " + ", ".join(pt(p) for p in data) + " } }")
            else:
                cx, cy, r = data
                draw.append(f".{{ .circle = .{{ .c = {pt((cx, cy))}, .r = {r} }} }}")
        role_s = f", .role = .{role}" if role else ""
        out.append(f'        .{{ .name = "{cls}"{role_s}, .terminals = .{{ {", ".join(terms)} }}, .draw = .{{ {", ".join(draw)} }} }},')
    out += ["    },", "}"]
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "/usr/share/xschem/xschem_library/devices")
